// Targeted by JavaCPP version 1.5.1: DO NOT EDIT THIS FILE

package io.github.accia.global;

import io.github.accia.*;

import org.bytedeco.javacpp.*;

public class WinToastLib extends io.github.accia.presets.WinToastLib {
    static { Loader.load(); }

// Parsed from wintoastlib.cpp

/* * Copyright (C) 2016-2019 Mohammed Boujemaoui <mohabouje@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

// #include "wintoastlib.h"
// #include <memory>
// #include <assert.h>
// #include <unordered_map>
// #include <array>

// #pragma comment(lib,"shlwapi")
// #pragma comment(lib,"user32")

// #ifdef NDEBUG
//     #define DEBUG_MSG(str) do { } while ( false )
// #else
//     #define DEBUG_MSG(str) do { std::wcout << str << std::endl; } while( false )
// #endif

// #define DEFAULT_SHELL_LINKS_PATH	L"\\Microsoft\\Windows\\Start Menu\\Programs\\"
// #define DEFAULT_LINK_FORMAT			L".lnk"
// #define STATUS_SUCCESS (0x00000000)


// Quickstart: Handling toast activations from Win32 apps in Windows 10
// https://blogs.msdn.microsoft.com/tiles_and_toasts/2015/10/16/quickstart-handling-toast-activations-from-win32-apps-in-windows-10/

    // Function load a function from library

    

    

    


    

    


    

    

    

    

    

    













































//
// Available as of Windows 10 Anniversary Update
// Ref: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts
//
// NOTE: This will add a new text field, so be aware when iterating over
//       the toast's text fields or getting a count of them.
//






































































}
